<a href="https://colab.research.google.com/github/fouziasharkar/Python-Libraries/blob/main/Task_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
a = np.zeros(11)
print(a)
print()
a[5]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [5]:
num1=int(input('Enter a number: '))
num2=int(input('Enter a number: '))

a = np.random.random((num1,num2))
print()
print(a)
print()

#if i want to generate random rumbers between 10-20
b = 10+ np.random.random((3,4))*10
print('multiplying by 10 scales the number from [0,1] -> [0,10] and adding 10 shifts the number from [0,10] -> [10,20]')
print(b)

Enter a number: 3
Enter a number: 4

[[0.72370486 0.05682488 0.79429154 0.89914564]
 [0.03302612 0.29274871 0.98353625 0.97635264]
 [0.7584841  0.02672052 0.54062175 0.33270455]]

multiplying by 10 scales the number from [0,1] -> [0,10] and adding 10 shifts the number from [0,10] -> [10,20]
[[19.58446439 12.50318735 18.97901118 12.01993891]
 [17.17173722 14.4606567  12.61814293 14.66983747]
 [17.21815241 16.58551096 14.84581256 18.53016959]]


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [95]:
def array_2D(a,b):

  p1=np.ones((a,b))
  print('p1:','\n',p1)
  print()


  p1[1:a-1,1:b-1]=0
  print('Edited_p1:', '\n',p1)

array_2D(4,4)


p1: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Edited_p1: 
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [96]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [97]:
#Code here
#No we can not create identity matrix of shape (3,4) because identity matrix are always square matrix
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [98]:
#Code here
m = np.zeros((5,5))
m+=np.arange(5)

print(m)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [94]:
m = np.random.randint(1,100,(10,2))
print(m)
print()
point = np.array([2,3])
eucladian_distance = np.sqrt(np.sum((m-point)**2,axis=1)).astype(int)
print(eucladian_distance)


[[32 17]
 [10 81]
 [43 53]
 [18 51]
 [47 26]
 [21 52]
 [42 21]
 [54 50]
 [ 8 63]
 [36  3]]

[33 78 64 50 50 52 43 70 60 34]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [93]:
#Code here
m = np.zeros((6,7,8))
i = np.unravel_index(100,(6,7,8))
print(i)
print(m)

(1, 5, 4)
[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]



### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [92]:
#Code here
m = np.array([1, 2, 3, 4, -8, -10],dtype=float)

reversed = m[::-1]
print(reversed)

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [91]:
#Code here
a = np.arange(12).reshape(3,4)
print(a,'\n')
np.size(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



12

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [99]:
#Code here
def softmax(array):

  if type(array) != np.ndarray:
    raise TypeError('Requires numpy array')
  elif array.ndim>1:
    raise TypeError('Requires 1D array')
  else:
    return np.exp(array)/np.sum(np.exp(array))


softmax(np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278]))

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

In [ ]:
s = np.array([1,2,3])
print(type(s))

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
def v_stack(*args):
  for i in args:
    if type(i) != np.ndarray:
      raise TypeError('Requires numpy array')
    else:
      m = np.vstack(args)


  return m

v_stack(np.array([1,2,3]),np.array([4,5,6]))

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [6]:
#Code here
#Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates.
#The function only accept 2 strings, otherwise raise error. The date format should be like this only:
#2022-12-6. The end date should be included and for simplicity, choose dates from a same year.

def date_array(start,end):
  if type(start)!=str and type(end)!=str:
    raise TypeError('Inputs should be string')

  # Convert string dates to numpy datetime64 format
  start_date = np.datetime64(start)
  end_date = np.datetime64(end)
  m=np.arange(start_date,end_date+np.timedelta64(1, 'D'),dtype='datetime64[D]')
  return m


print(date_array(start = '2020-09-15', end = '2020-09-25'))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


###`Q-14:` Subtract the mean of each row from a matrix.

In [7]:
#code here
mat = np.linspace(10,60,20,dtype='int').reshape(5,4)
print(mat,'\n')

mn = np.mean(mat,axis=1,keepdims=True).astype(int)
print(mn,'\n')

mat-mn

[[10 12 15 17]
 [20 23 25 28]
 [31 33 36 38]
 [41 44 46 49]
 [52 54 57 60]] 

[[13]
 [24]
 [34]
 [45]
 [55]] 



array([[-3, -1,  2,  4],
       [-4, -1,  1,  4],
       [-3, -1,  2,  4],
       [-4, -1,  1,  4],
       [-3, -1,  2,  5]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

In [12]:
m = np.linspace(10,60,16,dtype='int').reshape(4,4)
print(m,'\n')
m[:,[0,1]]=m[:,[1,0]]
print(m)

[[10 13 16 20]
 [23 26 30 33]
 [36 40 43 46]
 [50 53 56 60]] 

[[13 10 16 20]
 [26 23 30 33]
 [40 36 43 46]
 [53 50 56 60]]


###`Q-16:` Replace odd elements in arrays with -1.

In [13]:
#Code here

In [18]:
m
m[m%2==1]=-1
m

array([[-1, 10, 16, 20],
       [26, -1, 30, -1],
       [40, 36, -1, 46],
       [-1, 50, 56, 60]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

In [43]:
a=np.array([2,3,1,5,8])
b=np.array([3,2,1,7,2])


In [44]:
a[b>a]=b[a<b]
a

array([3, 3, 1, 7, 8])

In [40]:
b>a

array([False, False, False, False, False])

In [31]:
a<b

array([False, False, False,  True, False])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [59]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[9801, 6953, 9456,  634, 9406],
       [3090, 8698, 1081, 6326, 7677],
       [3118, 5884, 3263, 5093, 7194],
       [3385, 7895, 6108, 5331, 4909],
       [5622, 9803, 6114, 2411, 1279],
       [3659, 6733, 4339, 5377, 8885],
       [2533,  136, 7127, 6448, 1352],
       [8429, 3554, 8538, 9425, 7802]])

In [60]:
arr1[:,::2]

array([[9801, 9456, 9406],
       [3090, 1081, 7677],
       [3118, 3263, 7194],
       [3385, 6108, 4909],
       [5622, 6114, 1279],
       [3659, 4339, 8885],
       [2533, 7127, 1352],
       [8429, 8538, 7802]])

In [61]:

np.min(arr1)


136

In [62]:
np.max(arr1)

9803

In [63]:
arr1-np.min(arr1)

array([[9665, 6817, 9320,  498, 9270],
       [2954, 8562,  945, 6190, 7541],
       [2982, 5748, 3127, 4957, 7058],
       [3249, 7759, 5972, 5195, 4773],
       [5486, 9667, 5978, 2275, 1143],
       [3523, 6597, 4203, 5241, 8749],
       [2397,    0, 6991, 6312, 1216],
       [8293, 3418, 8402, 9289, 7666]])

In [65]:
np.max(arr1)-np.min(arr1)

9667

In [69]:
(arr1-arr1.min())/(arr1.max()-arr1.min())

array([[0.99979311, 0.70518258, 0.96410469, 0.05151546, 0.95893245],
       [0.30557567, 0.8856936 , 0.09775525, 0.64032275, 0.78007655],
       [0.30847212, 0.59460019, 0.3234716 , 0.51277542, 0.73011275],
       [0.33609186, 0.8026275 , 0.6177718 , 0.53739526, 0.4937416 ],
       [0.56749767, 1.        , 0.61839247, 0.23533671, 0.1182373 ],
       [0.36443571, 0.68242474, 0.43477811, 0.54215372, 0.90503776],
       [0.24795697, 0.        , 0.72318196, 0.652943  , 0.12578877],
       [0.85786697, 0.35357401, 0.86914244, 0.9608979 , 0.79300714]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [73]:
p = np.array([12,34,40,7,1,0])

In [83]:
def nth_largest_item(arr,n):

  if n>len(arr):
    raise IndexError('n is larger then array index')
  else:
    s = np.sort(arr)[::-1][n-1]
    print(s)


nth_largest_item(p,1)

40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here

In [84]:
a = np.array([1,2,3])

In [87]:
r=np.repeat(a,3)

In [88]:
t=np.tile(a,3)

In [90]:
np.hstack((r,t))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])