<a href="https://colab.research.google.com/github/fouziasharkar/Python-Libraries/blob/main/Task_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [2]:
m = np.random.randint(0,100,12).reshape(4,3)
m

array([[97, 61, 65],
       [91, 87, 21],
       [40, 22, 39],
       [80, 91, 66]])

In [3]:
#Sort this matrix. np.sort()
np.sort(m)

array([[61, 65, 97],
       [21, 87, 91],
       [22, 39, 40],
       [66, 80, 91]])

In [4]:
#Sort this matrix based on values in 2nd column.
#argsort()
#argsort gives the index value
np.argsort(m)

array([[1, 2, 0],
       [2, 1, 0],
       [1, 2, 0],
       [2, 0, 1]])

In [5]:
m[m[:,1].argsort()]

array([[40, 22, 39],
       [97, 61, 65],
       [91, 87, 21],
       [80, 91, 66]])

In [8]:
#Sort this matrix based on max value in each row.
sorted_matrix = sorted(m, key=lambda x: max(x))
sorted_matrix

[array([40, 22, 39]),
 array([91, 87, 21]),
 array([80, 91, 66]),
 array([97, 61, 65])]

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

Reshape to Column Vector: .reshape(-1, 1)

* The -1 in reshape means "unspecified" or "as many as needed". Here, it tells NumPy to automatically determine the number of rows based on the size of the array.
*   The 1 specifies that the reshaped array should have one column.




In [29]:
#Add marks every student of an extra subject in the same array.
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1,1)
extra_subject

array([[41],
       [87],
       [72],
       [36],
       [92]])

In [39]:
five_subject=np.concatenate((marks,extra_subject),axis=1)
five_subject


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [42]:
#Add two new students marks in respective 5 subjects.(one subject added in above task)

rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

new=np.vstack((five_subject, rec1,rec2))
new

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [47]:
#Add extra column with sum of all subjects(5-subjects) marks

sum=np.sum(new,axis=1).reshape(-1,1)

total=np.concatenate((new,sum),axis=1)
total

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [ ]:
#Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

In [55]:
total[np.argsort(total[:,5])]

array([[ 13,  10,   9,  33,  41, 106],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 63,  46,  90,  42,  87, 328],
       [ 92,  71,  52,  61,  53, 329],
       [ 77,  83,  98,  95,  89, 442]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
# code here

In [56]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [58]:
np.unique(arr,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [59]:
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [64]:
total

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [67]:
np.flip(total,axis=[0,1])

array([[329,  53,  61,  52,  71,  92],
       [442,  89,  95,  98,  83,  77],
       [315,  92,  36,  59,  61,  67],
       [234,  36,  78,  29,   9,  82],
       [229,  72,  29,  13,  76,  39],
       [328,  87,  42,  90,  46,  63],
       [106,  41,  33,   9,  10,  13]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [73]:
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

X = 6
arr

array([[ 1,  2,  3,  4,  5],
       [10, -3, 30,  4,  5],
       [ 3,  2,  5, -4,  5],
       [ 9,  7,  3,  6,  5]])

In [78]:
row,col=np.where(arr>X)
print(row)
np.unique(row)

[1 1 3 3]


array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [60]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [61]:
arr3

array([7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [ ]:
# code here
#seed()function initialize the random numbers

In [105]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [115]:
np.unravel_index(np.argmax(arr), arr.shape)

(0, 39)

In [109]:
max_index = np.unravel_index(np.argmax(arr), arr.shape)
min_index = np.unravel_index(np.argmin(arr), arr.shape)

In [111]:
arr[max_index] = 0
arr[min_index] = 0
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957,   0, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318,   0, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

np.clip(arr, 100, 200) ensures that all values in arr are limited to the range [100, 200].

-> Values less than 100 are replaced with 100.

-> Values greater than 200 are replaced with 200.

-> The original array arr remains unchanged, and arr_clipped contains the values after clipping.

In [121]:
m = np.random.randint(0,1000,200)
m

array([606, 793, 711,   2, 462, 917, 341, 814, 696, 316,  21, 240, 540,
        37, 720, 647, 915, 559, 179,  64, 795, 141, 406, 379, 459, 965,
       308, 143, 143, 870, 644,  97, 365, 295, 974, 628, 287, 637, 360,
       776,  87, 278,  65, 673, 555, 645, 152, 589, 640, 934,  51, 900,
       409, 216, 188, 565,  48, 190, 410, 885, 767, 520, 163, 355, 371,
       998, 234, 371, 617, 498, 881, 300, 201, 429, 262, 683, 807, 408,
       172, 613, 563, 753, 469, 199, 879, 364, 456, 939, 292, 958, 601,
        89, 975, 413, 955, 447,  16,  42, 636, 220,  93, 858, 598, 989,
       642, 437, 364, 124, 226, 761, 163, 212, 264, 748, 153, 488, 787,
        57, 368, 376, 722, 606, 179, 303, 570, 279, 543, 271, 636, 408,
       641, 212, 150, 978,  76, 404, 201, 307, 555, 540, 186, 666, 178,
       216, 434, 876, 227, 248, 740, 143, 967, 805, 565, 347, 291,  71,
       394, 107, 176, 369, 936, 859, 612, 721, 574, 402, 176, 234, 751,
        42, 855,  50, 127, 792, 221, 485, 145, 468, 252, 989, 52

In [127]:
cliped = np.clip(arr,100,200)
cliped

array([[200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 181, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 137, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 100, 200, 200, 200, 200, 200, 173, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 171, 200, 178, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 100, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 117, 200, 200, 123,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 191, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 136, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
        200, 200, 200, 193, 200, 200, 200, 200, 200

In [129]:
np.cumsum(np.sort(cliped))

array([  100,   200,   317,   440,   576,   713,   884,  1057,  1235,
        1416,  1607,  1800,  1994,  2191,  2391,  2591,  2791,  2991,
        3191,  3391,  3591,  3791,  3991,  4191,  4391,  4591,  4791,
        4991,  5191,  5391,  5591,  5791,  5991,  6191,  6391,  6591,
        6791,  6991,  7191,  7391,  7591,  7791,  7991,  8191,  8391,
        8591,  8791,  8991,  9191,  9391,  9591,  9791,  9991, 10191,
       10391, 10591, 10791, 10991, 11191, 11391, 11591, 11791, 11991,
       12191, 12391, 12591, 12791, 12991, 13191, 13391, 13591, 13791,
       13991, 14191, 14391, 14591, 14791, 14991, 15191, 15391, 15591,
       15791, 15991, 16191, 16391, 16591, 16791, 16991, 17191, 17391,
       17591, 17791, 17991, 18191, 18391, 18591, 18791, 18991, 19191,
       19391, 19591, 19791, 19991, 20191, 20391, 20591, 20791, 20991,
       21191, 21391, 21591, 21791, 21991, 22191, 22391, 22591, 22791,
       22991, 23191, 23391, 23591, 23791, 23991, 24191, 24391, 24591,
       24791, 24991,

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [131]:
m = np.random.random(100)
m

array([0.59597461, 0.50070378, 0.74705818, 0.0957757 , 0.5925761 ,
       0.2283685 , 0.2840345 , 0.24061098, 0.41810516, 0.73831769,
       0.58997126, 0.79810743, 0.07951406, 0.46820052, 0.72700456,
       0.49052174, 0.31671761, 0.89496505, 0.10071009, 0.47315385,
       0.96389312, 0.27643703, 0.8503004 , 0.90104781, 0.39160194,
       0.83970974, 0.08983296, 0.67108208, 0.58553665, 0.35540109,
       0.60388336, 0.56247426, 0.94797428, 0.69219221, 0.46578484,
       0.37896912, 0.68611971, 0.7091585 , 0.23044348, 0.26957899,
       0.56314008, 0.9272328 , 0.31425778, 0.67149788, 0.80506766,
       0.88011676, 0.70666911, 0.26856021, 0.92263385, 0.22168888,
       0.95453407, 0.87014134, 0.48221985, 0.67794082, 0.57813679,
       0.67593511, 0.41017615, 0.31817756, 0.85240565, 0.45971054,
       0.6968306 , 0.49544442, 0.86938841, 0.84298395, 0.91549651,
       0.46405699, 0.71559042, 0.82374031, 0.19347073, 0.56310294,
       0.51612603, 0.40504472, 0.35524841, 0.47257587, 0.82606

In [135]:
r =m.round(3)
r

array([0.596, 0.501, 0.747, 0.096, 0.593, 0.228, 0.284, 0.241, 0.418,
       0.738, 0.59 , 0.798, 0.08 , 0.468, 0.727, 0.491, 0.317, 0.895,
       0.101, 0.473, 0.964, 0.276, 0.85 , 0.901, 0.392, 0.84 , 0.09 ,
       0.671, 0.586, 0.355, 0.604, 0.562, 0.948, 0.692, 0.466, 0.379,
       0.686, 0.709, 0.23 , 0.27 , 0.563, 0.927, 0.314, 0.671, 0.805,
       0.88 , 0.707, 0.269, 0.923, 0.222, 0.955, 0.87 , 0.482, 0.678,
       0.578, 0.676, 0.41 , 0.318, 0.852, 0.46 , 0.697, 0.495, 0.869,
       0.843, 0.915, 0.464, 0.716, 0.824, 0.193, 0.563, 0.516, 0.405,
       0.355, 0.473, 0.826, 0.252, 0.484, 0.14 , 0.729, 0.318, 0.656,
       0.633, 0.033, 0.094, 0.258, 0.423, 0.779, 0.593, 0.553, 0.072,
       0.736, 0.492, 0.38 , 0.31 , 0.093, 0.228, 0.198, 0.927, 0.424,
       0.086])

In [136]:
np.percentile(r,0)

0.033

In [138]:
np.percentile(r,100)

0.964

In [140]:
difference= np.percentile(r,51)-np.percentile(r,50)
difference

0.025630000000000153